name: guerrilla_mail
description: Quickly receive anonymous and temporary mails.

publish_to: 'none'

version: 0.1.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  bloc: ^7.1.0
  copy_with_extension: ^2.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_widget_from_html_core: ^0.7.0
  guerrilla_mail_api: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.10
  snapping_sheet: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.2
  copy_with_extension_gen: ^2.0.3
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.0

dependency_overrides:
  analyzer: ^2.2.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo-circle.png"
  adaptive_icon_background: "#673ab7"
  adaptive_icon_foreground: "assets/logo/transparent.png"
  image_path_ios: "assets/logo/logo-square.png"
  remove_alpha_ios: true
